---
- hosts: all
  tasks:
  - name: Install python-Scapy and dependencies
    apt: name={{ item }} update_cache=yes
    loop: ['python3-scapy', 'net-tools', 'python2.7', 'nmap', 'python3-pip','iperf']
    become: yes

  - name: Adjust arp table
    command: ip neighbor add 192.168.50.57 lladdr 08:00:27:00:00:07 dev enp0s8 nud permanent
    become: yes
  
  - name: Adjust clock timezone
    command: timedatectl set-timezone UTC
    become: yes