---
- hosts: all
  tasks:
  - name: Enable interface
    command: ifconfig enp0s9 up
    become: yes
  - name: Enable interface
    command: ifconfig enp0s10 up
    become: yes
  - name: Enable interface
    command: ifconfig enp0s16 up
    become: yes
  - name: Enable interface
    command: ifconfig enp0s17 up
    become: yes
  - name: Enable interface
    command: ifconfig enp0s18 up
    become: yes
  - name: Adjust clock timezone
    command: timedatectl set-timezone UTC
    become: yes
  - name: Compile p4 code
    command: p4c -b bmv2 /vagrant/code/int.p4 -o /vagrant/code/int.bmv2
    become: yes
  - name: Start Bmv2 Switch
    shell: simple_switch --device-id 3 --thrift-port 9090 --interface 0@enp0s9 --interface 1@enp0s10 --interface 2@enp0s16 --interface 3@enp0s17 --interface 4@enp0s18  /vagrant/code/int.bmv2/int.json &
    async: 1000
    poll: 5
    become: yes
  - name: Insert entries in switch table by control plane
    shell: cat /vagrant/code/table3.txt | simple_switch_CLI
    become: yes
  - name: Turn off GSO, TSO and GRO
    command: ethtool --offload enp0s9 gso off tso off gro off
    become: yes
  - name: Turn off GSO, TSO and GRO
    command: ethtool --offload enp0s10 gso off tso off gro off
    become: yes
  - name: Turn off GSO, TSO and GRO
    command: ethtool --offload enp0s16 gso off tso off gro off
    become: yes
  - name: Turn off GSO, TSO and GRO
    command: ethtool --offload enp0s17 gso off tso off gro off
    become: yes
  - name: Turn off GSO, TSO and GRO
    command: ethtool --offload enp0s18 gso off tso off gro off
    become: yes